name: car_workflow
on :
  workflow_call:
jobs:
  cd:
    runs-on: ubuntu-latest
    steps:
      - name: Step 7 - Deploy to CF
        uses: jhunt/cf-push@v1
        with:
          api: https://api.cf.ap21.hana.ondemand.com
          username: ramyaravindra999@gmail.com
          password: Azuredevops@123
          org: 6fece677trial
          space: prod
          manifest: manifest.yml
