
name: Pipeline

on:
  push:
    branches: [ branch_jfrog ]
    
#starting buildjob
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Step 1 - Checkout main branch from GitHub 
        uses: actions/checkout@v2
                
      - name: Step 2 - Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 17
                  
      - name: Step3 - Build with Gradle
        uses: gradle/gradle-build-action@4137be6a8bf7d7133955359dbd952c0ca73b1021
        with:
          arguments: build
      - run: |
          echo "-------"
          ls '${{ github.workspace }}'/build/libs
          ls '${{ github.workspace }}'
                 
      - name: Step5 Jfrog artifactory
        uses: jfrog/setup-jfrog-cli@v2.0.0
        env:
          JF_ARTIFACTORY_1: 18.219.130.61:8082
      - run: |
          jfrog rt ping
      
        


