
name: Pipeline

on:
  push:
    branches: [ branch_checkingout-other-repo ]
    
#starting buildjob
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Step 1 - Checkout main branch from GitHub 
        uses: actions/checkout@v2
        with:
          repository: org-Santhosh/privaterepo
          token: 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
